# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff9a0e98ae7b8d45c5fcecd13619ead2704deabbe9033287987eaf5591be72e05f1ba1498e624f3c55496f5793685da7e36ffecb049b1fb0e7eb6e24ca8f3819

test:
  secret_key_base: 2ff34c757cf8dc6c9b4cca22a7d777125d5eee14a6b71e384671cc9c1c58a261ae04eb408bf1175ae0a142697f8bd743a9063bc1d6705038a5423f0b8e941ef6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
